### ISSUE TITLE
How was Lidar-Camera calibration done ?

### ISSUE THREAD

**Issue by adityag6994** [unmannedlab/UWB_Dataset#1]
Thanks for sharing dataset with community!

Can you please tell how was Lidar-Camera calibration done ?

**Comment by adityag6994** [comment]
Also, was there any hardware synchronization during lidar-camera calibration ?

**Comment by jh0329** [comment]
> Thanks for sharing dataset with community!
> 
> Can you please tell how was Lidar-Camera calibration done ?

Thanks for your interest in this dataset, we will add Lidar-Camera calibration results soon.

**Comment by adityag6994** [comment]
@jh0329  thanks, looking forward to them :)
