### ISSUE TITLE
How to Read and Realize VectorNav VN-300 Data with ROS

### ISSUE THREAD

**Issue by oceanechy** [unmannedlab/UWB_Dataset#3]
Thank you very much for your work. I am currently facing some issues regarding how ROS can read and retrieve data from VectorNav VN-300. If you could help me, that would be greatly appreciated

**Comment by jh0329** [comment]
> Thank you very much for your work. I am currently facing some issues regarding how ROS can read and retrieve data from VectorNav VN-300. If you could help me, that would be greatly appreciated

Sure! You can directly read the data from terminal by playing a bagfile.
(Terminal 1) $ roscore
(Terminal 2) $ rosbag play <bag file>
(Terminal 3) $ rostopic list 
(Terminal 3) $ rostopic echo <topic name>

If you want to retrieve the data and use them for downstream work, please refer to http://wiki.ros.org/rosbag/Code%20API
to use API.
